import Foundation

extension Opportunity {
    func withOrderState(_ state: OrderExecutionState, submittedPrice: Double, submittedShares: Int) -> Opportunity {
        Opportunity(
            rank: rank,
            symbol: symbol,
            market: market,
            sector: sector,
            aiScore: aiScore,
            confidence: confidence,
            safety: safety,
            probabilityOfSuccess: probabilityOfSuccess,
            newsScore: newsScore,
            recommendedShares: submittedShares,
            price: price,
            brokerFee: brokerFee,
            expectedProfit: expectedProfit,
            prospect: prospect,
            timeToTarget: timeToTarget,
            timeWindow: timeWindow,
            catalystBucket: catalystBucket,
            sourceTrigger: sourceTrigger,
            dataOrigin: dataOrigin,
            sourceSummary: sourceSummary,
            reviewSummary: reviewSummary,
            intelligenceDrivers: intelligenceDrivers,
            intelligenceChannels: intelligenceChannels,
            urgency: urgency,
            priceChangePercent: priceChangePercent,
            targetFitLabel: targetFitLabel,
            speedLabel: speedLabel,
            capitalFitLabel: capitalFitLabel,
            dataQualityLabel: dataQualityLabel,
            analysisTimestamp: analysisTimestamp,
            dataTimestamp: dataTimestamp,
            lastRefreshTimestamp: lastRefreshTimestamp,
            brokerName: brokerName,
            orderState: state,
            submittedPrice: submittedPrice,
            submittedShares: submittedShares,
            decisionBias: decisionBias,
            aggressionMode: aggressionMode,
            marketRegime: marketRegime,
            targetPressureLabel: targetPressureLabel,
            capitalDisciplineLabel: capitalDisciplineLabel,
            allocationPercent: allocationPercent,
            positionSizePercent: positionSizePercent,
            conviction: conviction,
            permission: permission,
            rotationBias: rotationBias,
            hungerMode: hungerMode,
            executionStyle: executionStyle,
            commandText: commandText,
            priorityScore: priorityScore,
            targetDirective: targetDirective,
            targetCoveragePercent: targetCoveragePercent,
            sourceReliabilityScore: sourceReliabilityScore,
            shareReliabilityScore: shareReliabilityScore,
            optionsFlowStrength: optionsFlowStrength,
            darkPoolStrength: darkPoolStrength,
            insiderStrength: insiderStrength,
            filingStrength: filingStrength,
            earningsEventRisk: earningsEventRisk,
            macroEventRisk: macroEventRisk,
            trustState: trustState,
            trustReason: trustReason,
            buyReason: buyReason,
            rotationReason: rotationReason,
            warningReason: warningReason,
            advancedSignal: advancedSignal,
            previousAiScore: previousAiScore,
            previousConfidence: previousConfidence
        )
    }

    func withTimestamps(analysisTimestamp: Date, dataTimestamp: Date, lastRefreshTimestamp: Date) -> Opportunity {
        Opportunity(
            rank: rank,
            symbol: symbol,
            market: market,
            sector: sector,
            aiScore: aiScore,
            confidence: confidence,
            safety: safety,
            probabilityOfSuccess: probabilityOfSuccess,
            newsScore: newsScore,
            recommendedShares: recommendedShares,
            price: price,
            brokerFee: brokerFee,
            expectedProfit: expectedProfit,
            prospect: prospect,
            timeToTarget: timeToTarget,
            timeWindow: timeWindow,
            catalystBucket: catalystBucket,
            sourceTrigger: sourceTrigger,
            dataOrigin: dataOrigin,
            sourceSummary: sourceSummary,
            reviewSummary: reviewSummary,
            intelligenceDrivers: intelligenceDrivers,
            intelligenceChannels: intelligenceChannels,
            urgency: urgency,
            priceChangePercent: priceChangePercent,
            targetFitLabel: targetFitLabel,
            speedLabel: speedLabel,
            capitalFitLabel: capitalFitLabel,
            dataQualityLabel: dataQualityLabel,
            analysisTimestamp: analysisTimestamp,
            dataTimestamp: dataTimestamp,
            lastRefreshTimestamp: lastRefreshTimestamp,
            brokerName: brokerName,
            orderState: orderState,
            submittedPrice: submittedPrice,
            submittedShares: submittedShares,
            decisionBias: decisionBias,
            aggressionMode: aggressionMode,
            marketRegime: marketRegime,
            targetPressureLabel: targetPressureLabel,
            capitalDisciplineLabel: capitalDisciplineLabel,
            allocationPercent: allocationPercent,
            positionSizePercent: positionSizePercent,
            conviction: conviction,
            permission: permission,
            rotationBias: rotationBias,
            hungerMode: hungerMode,
            executionStyle: executionStyle,
            commandText: commandText,
            priorityScore: priorityScore,
            targetDirective: targetDirective,
            targetCoveragePercent: targetCoveragePercent,
            sourceReliabilityScore: sourceReliabilityScore,
            shareReliabilityScore: shareReliabilityScore,
            optionsFlowStrength: optionsFlowStrength,
            darkPoolStrength: darkPoolStrength,
            insiderStrength: insiderStrength,
            filingStrength: filingStrength,
            earningsEventRisk: earningsEventRisk,
            macroEventRisk: macroEventRisk,
            trustState: trustState,
            trustReason: trustReason,
            buyReason: buyReason,
            rotationReason: rotationReason,
            warningReason: warningReason,
            advancedSignal: advancedSignal,
            previousAiScore: previousAiScore,
            previousConfidence: previousConfidence
        )
    }

    func withLastRefresh(_ lastRefreshTimestamp: Date) -> Opportunity {
        withTimestamps(
            analysisTimestamp: analysisTimestamp,
            dataTimestamp: dataTimestamp,
            lastRefreshTimestamp: lastRefreshTimestamp
        )
    }
}
