import SwiftUI

extension WealthEngineRefreshRanking {
    @MainActor
    static func makeOpportunity(
        blueprint: OpportunityBlueprint,
        sessionState: MarketSessionState,
        previousByKey: [String: Opportunity],
        refreshTime: Date,
        brokerStore: WealthBrokerStore,
        goals: WealthGoalVector,
        behavior: WealthBehaviorSettingsStore,
        buyingPower: Double,
        regime: WealthMarketRegime,
        holdings: [Holding],
        duplicateExposureCount: Int,
        currentOpenPositions: Int,
        dailyLossLocked: Bool,
        marketWideBrake: Bool,
        brokerCooldownActive: Bool
    ) -> Opportunity {
        let context = buildOpportunityContext(
            blueprint: blueprint,
            sessionState: sessionState,
            goals: goals,
            behavior: behavior,
            buyingPower: buyingPower,
            regime: regime,
            holdings: holdings,
            duplicateExposureCount: duplicateExposureCount,
            currentOpenPositions: currentOpenPositions,
            dailyLossLocked: dailyLossLocked,
            marketWideBrake: marketWideBrake,
            brokerCooldownActive: brokerCooldownActive
        )

        return Opportunity(
            rank: 0,
            symbol: blueprint.symbol,
            market: blueprint.market,
            sector: blueprint.sector,
            aiScore: context.scoreResult.score,
            confidence: context.scoreResult.confidence,
            safety: context.scoreResult.safety,
            probabilityOfSuccess: Int(round(blueprint.probability)),
            newsScore: blueprint.newsScore,
            recommendedShares: context.stagedShares,
            price: blueprint.price,
            brokerFee: context.pricing.buyFee,
            expectedProfit: context.scoreResult.expectedProfit,
            prospect: blueprint.prospect,
            timeToTarget: blueprint.timeToTarget,
            timeWindow: blueprint.timeWindow,
            catalystBucket: blueprint.catalystBucket,
            sourceTrigger: blueprint.sourceTrigger,
            dataOrigin: blueprint.dataOrigin,
            sourceSummary: blueprint.sourceSummary,
            reviewSummary: blueprint.reviewSummary,
            intelligenceDrivers: blueprint.intelligenceDrivers,
            intelligenceChannels: blueprint.intelligenceChannels,
            urgency: blueprint.urgency,
            priceChangePercent: blueprint.priceChangePercent,
            targetFitLabel: blueprint.targetFitLabel,
            speedLabel: blueprint.speedLabel,
            capitalFitLabel: blueprint.capitalFitLabel,
            dataQualityLabel: blueprint.dataQualityLabel,
            analysisTimestamp: refreshTime.addingTimeInterval(-blueprint.analysisAge),
            dataTimestamp: refreshTime.addingTimeInterval(-blueprint.dataAge),
            lastRefreshTimestamp: refreshTime,
            brokerName: brokerStore.selectedBroker.name,
            orderState: .ready,
            submittedPrice: max(0, blueprint.price + blueprint.submittedPriceOffset),
            submittedShares: context.stagedShares,
            decisionBias: context.decision,
            aggressionMode: context.selectionMode,
            marketRegime: regime,
            targetPressureLabel: WealthEngineStore.targetPressureLabel(goals),
            capitalDisciplineLabel: "DYNAMIC SIZE",
            allocationPercent: context.allocationPercent,
            positionSizePercent: context.positionSizePercent,
            conviction: context.conviction,
            permission: context.permission,
            rotationBias: context.rotation.bias,
            hungerMode: context.hungerMode,
            executionStyle: context.executionStyle,
            commandText: context.commandText,
            priorityScore: context.priorityScore,
            targetDirective: context.targetDirective,
            targetCoveragePercent: context.targetCoveragePercent,
            sourceReliabilityScore: context.sourceReliabilityScore,
            shareReliabilityScore: context.shareReliabilityScore,
            optionsFlowStrength: blueprint.optionsFlowStrength,
            darkPoolStrength: blueprint.darkPoolStrength,
            insiderStrength: blueprint.insiderStrength,
            filingStrength: blueprint.filingStrength,
            earningsEventRisk: blueprint.earningsEventRisk,
            macroEventRisk: blueprint.macroEventRisk,
            trustState: context.trustState,
            trustReason: context.trustReason,
            buyReason: WealthEngineStore.buyReason(
                for: blueprint,
                score: context.scoreResult.score,
                confidence: context.scoreResult.confidence,
                mode: context.selectionMode,
                goals: goals,
                advanced: context.advanced
            ),
            rotationReason: context.rotation.reason,
            warningReason: WealthEngineStore.warningReason(
                for: blueprint,
                score: context.scoreResult.score,
                confidence: context.scoreResult.confidence,
                regime: regime
            ),
            advancedSignal: context.advanced,
            previousAiScore: previousByKey[wealthRefreshIdentityKey(symbol: blueprint.symbol, market: blueprint.market)]?.aiScore,
            previousConfidence: previousByKey[wealthRefreshIdentityKey(symbol: blueprint.symbol, market: blueprint.market)]?.confidence
        )
    }
}
