import Foundation

extension WealthPortfolioStore {
    static func persistedHolding(from holding: Holding) -> PersistedHolding {
        PersistedHolding(
            symbol: holding.symbol,
            market: holding.market,
            sector: holding.sector,
            shares: holding.shares,
            averagePrice: holding.averagePrice,
            currentPrice: holding.effectiveCurrentPrice,
            aiScore: holding.aiScore,
            aiBand: holding.aiBand,
            confidence: holding.confidence,
            safety: holding.safety,
            prospect: holding.prospect,
            timeWindow: holding.timeWindow,
            riskLabel: holding.riskLabel,
            holdLabel: holding.holdLabel,
            safeKeepLabel: holding.safeKeepLabel,
            lockLabel: holding.lockLabel,
            sourceTrigger: holding.sourceTrigger,
            dataOrigin: holding.dataOrigin,
            reviewSummary: holding.reviewSummary,
            researchSummary: holding.researchSummary,
            analysisTimestamp: holding.analysisTimestamp,
            dataTimestamp: holding.dataTimestamp,
            lastRefreshTimestamp: holding.lastRefreshTimestamp,
            filledAt: holding.filledAt,
            orderIntentRaw: holding.orderIntent.rawValue,
            orderStateRaw: holding.orderState.rawValue,
            pendingShares: holding.pendingShares,
            submittedExitPrice: holding.submittedExitPrice,
            orderSubmittedAt: holding.orderSubmittedAt
        )
    }

    static func persistedOpportunity(from opportunity: Opportunity) -> PersistedOpportunity {
        PersistedOpportunity(
            rank: opportunity.rank,
            symbol: opportunity.symbol,
            market: opportunity.market,
            sector: opportunity.sector,
            aiScore: opportunity.aiScore,
            confidence: opportunity.confidence,
            safety: opportunity.safety,
            probabilityOfSuccess: opportunity.probabilityOfSuccess,
            newsScore: opportunity.newsScore,
            recommendedShares: opportunity.recommendedShares,
            price: opportunity.price,
            brokerFee: opportunity.brokerFee,
            expectedProfit: opportunity.expectedProfit,
            prospect: opportunity.prospect,
            timeToTarget: opportunity.timeToTarget,
            timeWindow: opportunity.timeWindow,
            catalystBucket: opportunity.catalystBucket,
            sourceTrigger: opportunity.sourceTrigger,
            dataOrigin: opportunity.dataOrigin,
            sourceSummary: opportunity.sourceSummary,
            reviewSummary: opportunity.reviewSummary,
            intelligenceDrivers: opportunity.intelligenceDrivers,
            intelligenceChannels: opportunity.intelligenceChannels,
            urgency: opportunity.urgency,
            priceChangePercent: opportunity.priceChangePercent,
            targetFitLabel: opportunity.targetFitLabel,
            speedLabel: opportunity.speedLabel,
            capitalFitLabel: opportunity.capitalFitLabel,
            dataQualityLabel: opportunity.dataQualityLabel,
            analysisTimestamp: opportunity.analysisTimestamp,
            dataTimestamp: opportunity.dataTimestamp,
            lastRefreshTimestamp: opportunity.lastRefreshTimestamp,
            brokerName: opportunity.brokerName,
            orderStateRaw: opportunity.orderState.rawValue,
            submittedPrice: opportunity.submittedPrice,
            submittedShares: opportunity.submittedShares,
            actualExitPrice: opportunity.actualExitPrice,
            actualRealizedProfit: opportunity.actualRealizedProfit,
            actualRealizedNetProfit: opportunity.actualRealizedNetProfit,
            completedAt: opportunity.completedAt,
            decisionBiasRaw: opportunity.decisionBias.rawValue,
            aggressionModeRaw: opportunity.aggressionMode.rawValue,
            marketRegimeRaw: opportunity.marketRegime.rawValue,
            targetPressureLabel: opportunity.targetPressureLabel,
            capitalDisciplineLabel: opportunity.capitalDisciplineLabel,
            allocationPercent: opportunity.allocationPercent,
            positionSizePercent: opportunity.positionSizePercent,
            convictionRaw: opportunity.conviction.rawValue,
            permissionRaw: opportunity.permission.rawValue,
            rotationBiasRaw: opportunity.rotationBias.rawValue,
            hungerModeRaw: opportunity.hungerMode.rawValue,
            executionStyleRaw: opportunity.executionStyle.rawValue,
            commandText: opportunity.commandText,
            priorityScore: opportunity.priorityScore,
            targetDirective: opportunity.targetDirective,
            targetCoveragePercent: opportunity.targetCoveragePercent,
            sourceReliabilityScore: opportunity.sourceReliabilityScore,
            shareReliabilityScore: opportunity.shareReliabilityScore,
            optionsFlowStrength: opportunity.optionsFlowStrength,
            darkPoolStrength: opportunity.darkPoolStrength,
            insiderStrength: opportunity.insiderStrength,
            filingStrength: opportunity.filingStrength,
            earningsEventRisk: opportunity.earningsEventRisk,
            macroEventRisk: opportunity.macroEventRisk,
            trustStateRaw: opportunity.trustState.rawValue,
            trustReason: opportunity.trustReason,
            buyReason: opportunity.buyReason,
            rotationReason: opportunity.rotationReason,
            warningReason: opportunity.warningReason
        )
    }

    static func seededHoldings() -> [Holding] {
        []
    }
}
