import Foundation

enum WealthPortfolioExecutionSnapshots {
    static func completedBuySnapshot(from holding: Holding, completedAt: Date) -> Opportunity {
        let grossProfit = 0.0

        return Opportunity(
            rank: max(holding.aiBand, 1),
            symbol: holding.symbol,
            market: holding.market,
            sector: holding.sector,
            aiScore: holding.aiScore,
            confidence: holding.confidence,
            safety: holding.safety,
            probabilityOfSuccess: max(holding.confidence, holding.safety),
            newsScore: 0,
            recommendedShares: holding.shares,
            price: holding.effectiveCurrentPrice,
            brokerFee: WealthScoringEngine.feeEstimate(for: Double(holding.shares) * holding.averagePrice),
            expectedProfit: grossProfit,
            prospect: holding.prospect,
            timeToTarget: holding.holdLabel,
            timeWindow: holding.timeWindow,
            catalystBucket: "Completed Buy",
            sourceTrigger: holding.sourceTrigger,
            dataOrigin: holding.dataOrigin,
            sourceSummary: holding.researchSummary,
            reviewSummary: holding.reviewSummary,
            intelligenceDrivers: [],
            intelligenceChannels: [],
            urgency: "COMPLETED",
            priceChangePercent: holding.percentChange,
            targetFitLabel: "FILLED",
            speedLabel: "DONE",
            capitalFitLabel: "DEPLOYED",
            dataQualityLabel: "LIVE",
            analysisTimestamp: holding.analysisTimestamp,
            dataTimestamp: holding.dataTimestamp,
            lastRefreshTimestamp: completedAt,
            brokerName: WealthBrokerStore.shared.selectedBroker.name,
            orderState: .filled,
            submittedPrice: holding.averagePrice,
            submittedShares: holding.shares,
            decisionBias: .buy,
            aggressionMode: .moderate,
            marketRegime: .balanced,
            targetPressureLabel: holding.safeKeepLabel,
            capitalDisciplineLabel: holding.lockLabel,
            allocationPercent: 0,
            positionSizePercent: 0,
            conviction: .strong,
            permission: .go,
            rotationBias: .keep,
            hungerMode: .stalk,
            executionStyle: .staged,
            commandText: "BUY COMPLETED",
            priorityScore: holding.aiScore,
            targetDirective: holding.safeKeepLabel,
            targetCoveragePercent: 0,
            sourceReliabilityScore: holding.confidence,
            shareReliabilityScore: holding.safety,
            optionsFlowStrength: 0,
            darkPoolStrength: 0,
            insiderStrength: 0,
            filingStrength: 0,
            earningsEventRisk: 0,
            macroEventRisk: 0,
            trustState: .verified,
            trustReason: "Completed buys are persisted so recent activity stays stable between scans and app relaunches.",
            buyReason: holding.aiCommentary,
            rotationReason: holding.holdLabel,
            warningReason: "",
            advancedSignal: .neutral,
            previousAiScore: nil,
            previousConfidence: nil
        )
    }

    static func completedSellSnapshot(from holding: Holding, completedAt: Date) -> Opportunity {
        let soldShares = max(holding.pendingShares, holding.shares)
        let exitPrice = holding.submittedExitPrice ?? holding.effectiveCurrentPrice
        let entrySubtotal = Double(soldShares) * holding.averagePrice
        let exitSubtotal = Double(soldShares) * exitPrice
        let grossProfit = exitSubtotal - entrySubtotal

        return Opportunity(
            rank: max(holding.aiBand, 1),
            symbol: holding.symbol,
            market: holding.market,
            sector: holding.sector,
            aiScore: holding.aiScore,
            confidence: holding.confidence,
            safety: holding.safety,
            probabilityOfSuccess: max(holding.confidence, holding.safety),
            newsScore: 0,
            recommendedShares: soldShares,
            price: exitPrice,
            brokerFee: WealthScoringEngine.feeEstimate(for: Double(soldShares) * holding.averagePrice),
            expectedProfit: grossProfit,
            prospect: holding.prospect,
            timeToTarget: holding.holdLabel,
            timeWindow: holding.timeWindow,
            catalystBucket: "Completed Sell",
            sourceTrigger: holding.sourceTrigger,
            dataOrigin: holding.dataOrigin,
            sourceSummary: holding.researchSummary,
            reviewSummary: holding.reviewSummary,
            intelligenceDrivers: [],
            intelligenceChannels: [],
            urgency: "COMPLETED",
            priceChangePercent: holding.percentChange,
            targetFitLabel: "SOLD",
            speedLabel: "DONE",
            capitalFitLabel: "RETURNED",
            dataQualityLabel: "LIVE",
            analysisTimestamp: holding.analysisTimestamp,
            dataTimestamp: holding.dataTimestamp,
            lastRefreshTimestamp: completedAt,
            brokerName: WealthBrokerStore.shared.selectedBroker.name,
            orderState: .filled,
            submittedPrice: exitPrice,
            submittedShares: soldShares,
            decisionBias: .avoid,
            aggressionMode: .protect,
            marketRegime: .defensive,
            targetPressureLabel: holding.safeKeepLabel,
            capitalDisciplineLabel: holding.lockLabel,
            allocationPercent: 0,
            positionSizePercent: 0,
            conviction: .strong,
            permission: .go,
            rotationBias: .rotate,
            hungerMode: .protect,
            executionStyle: .wait,
            commandText: "SELL COMPLETED",
            priorityScore: holding.aiScore,
            targetDirective: holding.safeKeepLabel,
            targetCoveragePercent: 0,
            sourceReliabilityScore: holding.confidence,
            shareReliabilityScore: holding.safety,
            optionsFlowStrength: 0,
            darkPoolStrength: 0,
            insiderStrength: 0,
            filingStrength: 0,
            earningsEventRisk: 0,
            macroEventRisk: 0,
            trustState: .verified,
            trustReason: "Completed sells are persisted so recent activity stays stable between scans and app relaunches.",
            buyReason: holding.aiCommentary,
            rotationReason: holding.holdLabel,
            warningReason: "",
            advancedSignal: .neutral,
            previousAiScore: nil,
            previousConfidence: nil
        )
    }
}
