name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Select Swift version
        uses: swiftlang/setup-swift@v1
        with:
          swift-version: "5.9"

      - name: Run tests
        run: swift test
